---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: swift:5.7.2-jammy@sha256:d3988f9bf2571587ea426ca4068ce15c00db15dfee0646217134fa7183a40dd2
    commands:
      - swift build

trigger:
  branch:
    - main
